--- # roles/scriptorium/tasks/main.yml

# As of 2015-07-04 - xvfb & firefox required by ingest process so that we can invoke
# firefox to fetch visualizations from the server.
- name: Install key packages
  apt: name={{ item }} state=latest
  become: yes
  with_items:
    - apache2
    - apache2-dev
    - chromium-browser
    - git
    - mysql-server-5.6
    - python-mysqldb
    - libapache2-mod-wsgi-py3
    - python3-pip
    - redis-server
    - redis-tools
    - unzip
    - xvfb

- name: Check if mysql-connector-python is installed
  command: dpkg-query -W mysql-connector-python-py3
  register: mysql_connector
  failed_when: mysql_connector.rc > 1
  changed_when: mysql_connector.rc == 1

- name: Download mysql-connector-python
  get_url: 
    url="http://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python-py3_2.0.4-1ubuntu14.04_all.deb"
    dest="/home/{{ ansible_env.USER }}/mysql-connector-python-py3_2.0.4-1ubuntu14.04_all.deb"
  when: mysql_connector.rc == 1

- name: Install mysql-connector-python
  apt: deb="/home/{{ ansible_env.USER }}/mysql-connector-python-py3_2.0.4-1ubuntu14.04_all.deb"
  become: true
  when: mysql_connector.rc == 1

- name: Extract chrome driver
  unarchive:
    src="http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip"
    dest=/usr/lib/chromium-browser/
    copy=no
  become: yes
  
- name: Make sure we've got the right permissions on the chromedriver
  file: path=/usr/lib/chromium-browser/chromedriver mode="u+rx,g+rx,o+rx"
  become: yes
    
- name: Ensure services are enabled
  become: yes
  service: name={{ item }} enabled=yes
  with_items:
    - apache2
    - redis-server

# Due to the many non-US characters we're capturing in this database, we need to
# make sure UTF8 is on!
- name: Configure MySQL for utf8
  become: yes
  lineinfile: state=present dest=/etc/mysql/my.cnf insertafter="\[mysqld\]" line="character_set_server=utf8"

# On the off chance that the previous action changed MySQL config, restart the server.
- name: Restart MySQL
  become: yes
  service: name=mysql state=restarted

# Grab everything for the site from GitHub and pull it over.
# "debug_machine" used to all for sharing of the same Git repository on both the
# host machine, and a target virtual machine, for debugging purposes.
- name: Copy over key files
  git: repo={{ git_repo_url }} dest=/var/www/cts force=no
  become: yes
  when: not debug_machine
  ignore_errors: True

- name: Update permissions to allow Apache to access the data
  file:
    path: /var/www/cts/coptic
    recurse: yes
    owner: www-data
    group: www-data
  become: yes
    
- name: Copy over Django settings
  template: src=settings.py.j2 dest=/var/www/cts/coptic/coptic/settings.py
  become: yes

- name: Create folder for logging items from Django
  file: path=/var/log/django/ owner="www-data" group="www-data" state=directory
  become: yes

- name: Install Python packages via pip3
  pip: requirements=/var/www/cts/coptic/requirements.txt executable=pip3
  become: yes

- name: Copy over Apache2 config
  copy: src=scriptorium.conf dest=/etc/apache2/conf-enabled/scriptorium.conf
  become: yes

- name: Create MySQL DB
  mysql_db: name=coptic state=present
  become: yes

# TODO - stick this password into a vault file.
- name: Create MySQL User
  mysql_user: name=coptic password={{ mysql_password }} priv=coptic.*:ALL
  become: yes

- name: Ensure Services are started
  become: yes
  service: name={{ item }} state=started
  with_items:
    - apache2
    - redis-server

# Invoke Django to create/migrate database to the current version.
- name: Create database tables
  command: python3 manage.py migrate
  args:
    chdir: /var/www/cts/coptic/
  become: yes
  become_user: www-data

# Useful clue from here:
# http://source.mihelac.org/2009/10/23/django-avoiding-typing-password-for-superuser/
- name: Create superuser if not exists
  shell: echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'carrie@carrieschroeder.com', '{{ superuser_password }}')" | python3 ./manage.py shell
  ignore_errors: yes
  become: yes
  become_user: www-data
  args:
    chdir: /var/www/cts/coptic
