language: python
python:
  - "3.4"
env:
  - DJANGO=1.7
install:
  - pip3 install -q Django==$DJANGO --use-mirrors
  - pip3 install pep8 --use-mirrors
  - pip3 install -q -e . --use-mirrors
script:
  - python setup.py test