# Generated by Django 5.1.3 on 2024-12-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0004_alter_corpus_id_alter_corpus_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='tt_dir',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='tt_dir_tree_id',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corpus',
            name='visualization_formats',
            field=models.TextField(default=''),
        ),
    ]
