# Generated by Django 5.1.3 on 2024-12-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0005_text_tt_dir_text_tt_dir_tree_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='document_cts_urn',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
