# Generated by Django 5.1.3 on 2024-12-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0006_text_document_cts_urn'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='tt_filename',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
