# Generated by Django 5.1.4 on 2025-01-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0007_text_tt_filename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialMeta',
        ),
    ]
