# Generated by Django 5.1.4 on 2025-01-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0008_delete_specialmeta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HtmlVisualizationFormat',
        ),
    ]
