# Generated by Django 5.1.4 on 2025-01-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0009_delete_htmlvisualizationformat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaOrder',
        ),
        migrations.AddField(
            model_name='corpus',
            name='author',
            field=models.TextField(db_index=True, default=''),
        ),
    ]
