# Generated by Django 5.1.5 on 2025-01-21 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0011_htmlvisualization_config_htmlvisualization_css_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htmlvisualization',
            name='html',
        ),
    ]
