# Generated by Django 5.1.5 on 2025-02-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0012_remove_htmlvisualization_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='order',
            field=models.IntegerField(default=999999),
        ),
    ]
