name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_django_5.txt

    - name: Run addcorpora.sh
      run: |
        chmod +x ./addcorpora.sh
        ./addcorpora.sh

    - name: Run tests
      run: python manage.py test -t .